export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ONE = 'FETCH_ONE';
export const NEW_PRODUCT = 'NEW_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
